version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/hack"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/hack/kapp"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/hack/ko"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/hack/kustomize"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/hack/ytt"
  schedule:
    interval: daily
