# permissions for end users to view mavenartifacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mavenartifact-viewer-role
rules:
- apiGroups:
  - source.apps.tanzu.vmware.com
  resources:
  - mavenartifacts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.apps.tanzu.vmware.com
  resources:
  - mavenartifacts/status
  verbs:
  - get
